import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import LoginForm from "./user/login";
import { useContext } from "react";
import { AuthContext } from "@/context/AuthContext";
import useAuth from "@/hook/useAuth";

export default function Home() {
  const { user } = useContext(AuthContext);
  const { logout } = useAuth();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        {user && user.head && (
          <>
            <Image src={user.head} width={100} height={100} />
            <div className="btn btn-primary" onClick={logout}>
              登出
            </div>
          </>
        )}
        {!user && "123"}
      </main>
    </>
  );
}
